name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write  # ✅ Grants write access for pushing to the repo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate the snake files
        uses: Platane/snk@v2
        id: snake-gif
        with:
          github_user_name: petxr

      - name: Push generated files to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output  # ✅ Ensure this is correct
          build_dir: dist
          keep_history: true
          commit_message: "Update snake animation"
